"""The verifier.

Every test here is a way a generated notice can be wrong. The example-based
tests cover the failures we thought of; the property tests assert the stronger
claim the project actually rests on, which is that *no* notice citing a factor
absent from the decision can pass, whatever it says.

The notices are hand-written rather than generated by a model. That is
deliberate: a verifier tested only against real model output is tested only
against the mistakes that model happens to make, and the ones that matter are
the mistakes it makes rarely.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Final

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from aae.domain.errors import VerificationPreconditionError
from aae.domain.models import (
    AdverseActionNotice,
    Citation,
    CreditDecision,
    Decision,
    Factor,
    FactorDirection,
    FactualClaim,
    ReasonStatement,
    ViolationCode,
)
from aae.jurisdiction.india_rbi import INDIA_RBI
from aae.retrieval.corpus import RBI_FAIR_PRACTICES_CODE, InMemoryCorpus, india_rbi_corpus
from aae.verification.rules import VerificationPolicy
from aae.verification.verifier import NoticeVerifier

APPLICATION_ID: Final[str] = "APP-1001"

ADVERSE_IDS: Final[tuple[str, ...]] = (
    "ANNUITY_INCOME_RATIO",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
)
FAVOURABLE_IDS: Final[tuple[str, ...]] = ("AMT_INCOME_TOTAL", "CREDIT_TERM")
KNOWN_IDS: Final[frozenset[str]] = frozenset(ADVERSE_IDS + FAVOURABLE_IDS)

FEATURE_VALUES: Final[dict[str, float | str | None]] = {
    "ANNUITY_INCOME_RATIO": 0.3064,
    "EXT_SOURCE_2": 0.2189,
    "EXT_SOURCE_3": 0.2450,
    "AMT_INCOME_TOTAL": 149_900.0,
    "CREDIT_TERM": 0.0630,
    "OCCUPATION_TYPE": "Laborers",
    "EXT_SOURCE_1": None,
}

# A real sentence from section 2.3 of the corpus.
REAL_QUOTE: Final[str] = "convey in writing to the applicant the reasons"

SAFE_TEXT: Final[str] = "Your repayment burden relative to income was high."


def _factor(factor_id: str, rank: int, direction: FactorDirection, shap: float) -> Factor:
    return Factor(
        factor_id=factor_id,
        display_name=factor_id.replace("_", " ").title(),
        value=FEATURE_VALUES.get(factor_id),
        shap_value=shap,
        direction=direction,
        rank=rank,
    )


@pytest.fixture(scope="module")
def decision() -> CreditDecision:
    return CreditDecision(
        application_id=APPLICATION_ID,
        probability_default=0.83,
        decision=Decision.DECLINE,
        threshold=0.15,
        model_version="xgb-test",
        feature_values=FEATURE_VALUES,
        factors=(
            _factor(ADVERSE_IDS[0], 1, FactorDirection.ADVERSE, 0.92),
            _factor(ADVERSE_IDS[1], 2, FactorDirection.ADVERSE, 0.81),
            _factor(ADVERSE_IDS[2], 3, FactorDirection.ADVERSE, 0.46),
            _factor(FAVOURABLE_IDS[0], 4, FactorDirection.FAVOURABLE, -0.22),
            _factor(FAVOURABLE_IDS[1], 5, FactorDirection.FAVOURABLE, -0.14),
        ),
        scored_at=datetime.now(UTC),
    )


@pytest.fixture(scope="module")
def verifier() -> NoticeVerifier:
    return NoticeVerifier(INDIA_RBI, india_rbi_corpus())


def notice(
    *,
    reason_ids: tuple[str, ...] = ADVERSE_IDS,
    reason_text: str = SAFE_TEXT,
    claims: tuple[FactualClaim, ...] = (),
    citations: tuple[Citation, ...] | None = None,
    elements: frozenset[str] | None = None,
    application_id: str = APPLICATION_ID,
    jurisdiction: str = "india_rbi",
) -> AdverseActionNotice:
    """Build a notice that is valid unless an argument makes it otherwise."""
    return AdverseActionNotice(
        application_id=application_id,
        jurisdiction=jurisdiction,
        principal_reasons=tuple(
            ReasonStatement(factor_id=factor_id, text=reason_text) for factor_id in reason_ids
        ),
        factual_claims=claims,
        citations=(
            citations
            if citations is not None
            else (
                Citation(
                    document_id=RBI_FAIR_PRACTICES_CODE,
                    section="2.3",
                    quoted_span=REAL_QUOTE,
                ),
            )
        ),
        declared_elements=(
            elements
            if elements is not None
            else frozenset(
                {
                    "principal_reasons",
                    "regulatory_basis",
                    "decision_statement",
                    "grievance_contact",
                }
            )
        ),
    )


def _codes(result) -> set[ViolationCode]:
    return {v.code for v in result.violations}


class TestAValidNotice:
    def test_passes(self, verifier, decision):
        result = verifier.verify(notice(), decision)
        assert result.passed, result.rendered_violations()
        assert result.violations == ()

    def test_passes_with_accurate_claims(self, verifier, decision):
        result = verifier.verify(
            notice(
                claims=(
                    FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=149_900.0),
                    FactualClaim(field_name="OCCUPATION_TYPE", stated_value="Laborers"),
                )
            ),
            decision,
        )
        assert result.passed, result.rendered_violations()


class TestFactorGrounding:
    def test_rejects_an_invented_factor(self, verifier, decision):
        result = verifier.verify(notice(reason_ids=("CRYPTOCURRENCY_HOLDINGS",)), decision)
        assert not result.passed
        assert ViolationCode.FACTOR_GROUNDING in _codes(result)

    def test_rejects_a_favourable_factor_given_as_a_reason(self, verifier, decision):
        """The subtle one: a true fact about the model, used as a false reason.

        Income counted *for* this applicant. Citing it as a reason for decline
        is a real factor pointed the wrong way, which a name-only check waves
        through.
        """
        result = verifier.verify(notice(reason_ids=("AMT_INCOME_TOTAL",)), decision)
        assert not result.passed
        assert any("counted in the applicant's favour" in v.detail for v in result.violations)

    def test_rejects_a_repeated_reason(self, verifier, decision):
        result = verifier.verify(notice(reason_ids=(ADVERSE_IDS[0], ADVERSE_IDS[0])), decision)
        assert not result.passed
        assert any("more than once" in v.detail for v in result.violations)

    def test_names_the_offending_factor(self, verifier, decision):
        result = verifier.verify(notice(reason_ids=("MADE_UP",)), decision)
        assert any(v.locator == "MADE_UP" for v in result.violations)


class TestValueAccuracy:
    def test_rejects_a_misstated_value(self, verifier, decision):
        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=250_000.0),)),
            decision,
        )
        assert not result.passed
        assert ViolationCode.VALUE_ACCURACY in _codes(result)

    def test_allows_presentation_rounding(self, verifier, decision):
        """Quoting 150,000 for a recorded 149,900 is rounding, not misstatement."""
        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=150_000.0),)),
            decision,
        )
        assert result.passed, result.rendered_violations()

    def test_a_zero_tolerance_policy_rejects_rounding(self, decision):
        strict = NoticeVerifier(
            INDIA_RBI, india_rbi_corpus(), VerificationPolicy(value_relative_tolerance=0.0)
        )
        result = strict.verify(
            notice(claims=(FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=150_000.0),)),
            decision,
        )
        assert not result.passed

    def test_rejects_a_claim_about_an_unscored_field(self, verifier, decision):
        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="SHOE_SIZE", stated_value=9.0),)), decision
        )
        assert not result.passed
        assert any("not part of this decision" in v.detail for v in result.violations)

    def test_rejects_a_claim_about_a_missing_value(self, verifier, decision):
        """EXT_SOURCE_1 was absent for this applicant; no figure can be stated."""
        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="EXT_SOURCE_1", stated_value=0.5),)), decision
        )
        assert not result.passed
        assert ViolationCode.VALUE_ACCURACY in _codes(result)

    def test_rejects_a_wrong_categorical_value(self, verifier, decision):
        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="OCCUPATION_TYPE", stated_value="Managers"),)),
            decision,
        )
        assert not result.passed


class TestCitationValidity:
    def test_rejects_a_provision_that_does_not_exist(self, verifier, decision):
        result = verifier.verify(
            notice(
                citations=(
                    Citation(
                        document_id=RBI_FAIR_PRACTICES_CODE,
                        section="99.9",
                        quoted_span="lenders must decline politely",
                    ),
                )
            ),
            decision,
        )
        assert not result.passed
        assert any("does not exist" in v.detail for v in result.violations)

    def test_rejects_a_fabricated_quotation(self, verifier, decision):
        """The provision is real; the words attributed to it are not."""
        result = verifier.verify(
            notice(
                citations=(
                    Citation(
                        document_id=RBI_FAIR_PRACTICES_CODE,
                        section="2.3",
                        quoted_span="the lender may decline for any reason whatsoever",
                    ),
                )
            ),
            decision,
        )
        assert not result.passed
        assert any("does not appear" in v.detail for v in result.violations)

    def test_rejects_an_unknown_document(self, verifier, decision):
        result = verifier.verify(
            notice(
                citations=(
                    Citation(document_id="invented-act-1999", section="1", quoted_span="anything"),
                )
            ),
            decision,
        )
        assert not result.passed

    def test_tolerates_whitespace_and_case(self, verifier, decision):
        result = verifier.verify(
            notice(
                citations=(
                    Citation(
                        document_id=RBI_FAIR_PRACTICES_CODE,
                        section="2.3",
                        quoted_span="  CONVEY   IN\n WRITING to the applicant\tthe reasons ",
                    ),
                )
            ),
            decision,
        )
        assert result.passed, result.rendered_violations()


class TestElementCoverage:
    def test_rejects_a_notice_with_no_regulatory_basis(self, verifier, decision):
        result = verifier.verify(notice(citations=()), decision)
        assert not result.passed
        assert ViolationCode.ELEMENT_COVERAGE in _codes(result)

    def test_rejects_an_undeclared_prose_element(self, verifier, decision):
        result = verifier.verify(
            notice(elements=frozenset({"principal_reasons", "regulatory_basis"})), decision
        )
        assert not result.passed
        missing = {v.locator for v in result.violations}
        assert {"decision_statement", "grievance_contact"} <= missing

    def test_rejects_an_element_this_jurisdiction_does_not_define(self, verifier, decision):
        """Guards against a model inventing compliance it was never asked for."""
        result = verifier.verify(
            notice(
                elements=frozenset(
                    {
                        "principal_reasons",
                        "regulatory_basis",
                        "decision_statement",
                        "grievance_contact",
                        "right_to_free_credit_report",
                    }
                )
            ),
            decision,
        )
        assert not result.passed
        assert any(v.locator == "right_to_free_credit_report" for v in result.violations)

    def test_structural_elements_are_not_taken_on_trust(self, verifier, decision):
        """Declaring an element does not make it present.

        The notice below declares every element while supplying no citation.
        A check that trusted the declaration would pass it.
        """
        result = verifier.verify(
            notice(
                citations=(),
                elements=frozenset(
                    {
                        "principal_reasons",
                        "regulatory_basis",
                        "decision_statement",
                        "grievance_contact",
                    }
                ),
            ),
            decision,
        )
        assert not result.passed
        assert any(v.locator == "regulatory_basis" for v in result.violations)


class TestProhibitedContent:
    @pytest.mark.parametrize(
        "text",
        [
            "Your application was declined because you are married.",
            "Applicants of your gender default more often.",
            "We considered your age when assessing this application.",
            "Your marital status was a factor.",
            "This reflects your religion and caste.",
            "As a female applicant, your risk profile is higher.",
            "You are 34 years old, which affected the outcome.",
        ],
    )
    def test_rejects_a_reason_referencing_a_protected_characteristic(
        self, verifier, decision, text: str
    ):
        result = verifier.verify(notice(reason_ids=(ADVERSE_IDS[0],), reason_text=text), decision)
        assert not result.passed
        assert ViolationCode.PROHIBITED_CONTENT in _codes(result)

    def test_rejects_a_protected_attribute_as_a_factor(self, verifier, decision):
        result = verifier.verify(notice(reason_ids=("CODE_GENDER",)), decision)
        assert not result.passed
        assert ViolationCode.PROHIBITED_CONTENT in _codes(result)

    @pytest.mark.parametrize(
        "text",
        [
            "Your repayment burden relative to income was high.",
            "A single payment of this size exceeds our threshold.",
            "Your credit bureau score was below our current requirement.",
        ],
    )
    def test_accepts_ordinary_lending_language(self, verifier, decision, text: str):
        """The patterns must not fire on legitimate wording.

        "A single payment" is why the prohibited list uses targeted phrases
        rather than bare words: a check that flagged "single" would make
        ordinary notices unpublishable.
        """
        result = verifier.verify(notice(reason_ids=(ADVERSE_IDS[0],), reason_text=text), decision)
        assert result.passed, result.rendered_violations()


class TestReasonCount:
    def test_rejects_more_reasons_than_permitted(self, verifier, decision):
        five = (*ADVERSE_IDS, *FAVOURABLE_IDS)
        result = verifier.verify(notice(reason_ids=five), decision)
        assert not result.passed
        assert ViolationCode.REASON_COUNT in _codes(result)

    def test_accepts_exactly_the_cap(self, verifier, decision):
        assert INDIA_RBI.max_principal_reasons == 4
        result = verifier.verify(notice(reason_ids=(*ADVERSE_IDS, FAVOURABLE_IDS[0])), decision)
        # Fails on grounding, not on count.
        assert ViolationCode.REASON_COUNT not in _codes(result)


class TestPreconditions:
    def test_rejects_a_notice_for_another_applicant(self, verifier, decision):
        with pytest.raises(VerificationPreconditionError, match="APP-9999"):
            verifier.verify(notice(application_id="APP-9999"), decision)

    def test_rejects_a_notice_for_another_jurisdiction(self, verifier, decision):
        with pytest.raises(VerificationPreconditionError, match="us_reg_b"):
            verifier.verify(notice(jurisdiction="us_reg_b"), decision)

    def test_rejects_a_notice_for_an_approved_application(self, verifier, decision):
        approved = decision.model_copy(update={"decision": Decision.APPROVE})
        with pytest.raises(VerificationPreconditionError, match="no adverse action"):
            verifier.verify(notice(), approved)

    def test_a_precondition_failure_is_not_a_violation(self, verifier, decision):
        """It must raise rather than return, so no repair attempt is wasted."""
        with pytest.raises(VerificationPreconditionError):
            verifier.verify(notice(application_id="APP-OTHER"), decision)


class TestEveryCheckRuns:
    def test_all_problems_are_reported_at_once(self, verifier, decision):
        """One violation per attempt would cost one model call per problem."""
        result = verifier.verify(
            notice(
                reason_ids=("INVENTED", "AMT_INCOME_TOTAL"),
                claims=(FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=1.0),),
                citations=(
                    Citation(document_id=RBI_FAIR_PRACTICES_CODE, section="9.9", quoted_span="x"),
                ),
                elements=frozenset({"principal_reasons"}),
            ),
            decision,
        )
        assert not result.passed
        assert {
            ViolationCode.FACTOR_GROUNDING,
            ViolationCode.VALUE_ACCURACY,
            ViolationCode.CITATION_VALIDITY,
            ViolationCode.ELEMENT_COVERAGE,
        } <= _codes(result)

    def test_attempt_number_is_recorded(self, verifier, decision):
        assert verifier.verify(notice(), decision, attempt=3).attempt == 3

    def test_violations_render_for_a_repair_prompt(self, verifier, decision):
        result = verifier.verify(notice(reason_ids=("INVENTED",)), decision)
        rendered = result.rendered_violations()
        assert rendered
        assert all(isinstance(line, str) and line for line in rendered)
        assert any("INVENTED" in line for line in rendered)


class TestProperties:
    """The claims that matter, asserted over generated input rather than examples."""

    @settings(max_examples=200)
    @given(
        st.lists(
            st.text(min_size=1, max_size=24).filter(lambda s: s.strip() and s not in KNOWN_IDS),
            min_size=1,
            max_size=3,
            unique=True,
        )
    )
    def test_no_notice_citing_an_unknown_factor_can_pass(self, fabricated: list[str]):
        """The central claim: fabrication is always caught.

        Whatever the model invents, and however plausible it reads, a reason
        naming a factor that did not contribute to this decision cannot get
        through.
        """
        verifier = NoticeVerifier(INDIA_RBI, india_rbi_corpus())
        result = verifier.verify(
            notice(reason_ids=(ADVERSE_IDS[0], *fabricated[:3])), _module_decision()
        )
        assert not result.passed
        assert ViolationCode.FACTOR_GROUNDING in _codes(result)

    @settings(max_examples=200)
    @given(st.floats(min_value=-1e9, max_value=1e9, allow_nan=False, allow_infinity=False))
    def test_a_value_outside_tolerance_is_always_caught(self, stated: float):
        actual = FEATURE_VALUES["AMT_INCOME_TOTAL"]
        assert isinstance(actual, float)
        verifier = NoticeVerifier(INDIA_RBI, india_rbi_corpus())

        result = verifier.verify(
            notice(claims=(FactualClaim(field_name="AMT_INCOME_TOTAL", stated_value=stated),)),
            _module_decision(),
        )
        within = abs(stated - actual) <= abs(actual) * 0.005
        assert result.passed == within

    @settings(max_examples=100)
    @given(st.sampled_from(FAVOURABLE_IDS))
    def test_no_favourable_factor_can_be_a_reason(self, favourable: str):
        verifier = NoticeVerifier(INDIA_RBI, india_rbi_corpus())
        result = verifier.verify(notice(reason_ids=(favourable,)), _module_decision())
        assert not result.passed

    @settings(max_examples=50)
    @given(st.integers(min_value=1, max_value=6))
    def test_verification_is_deterministic(self, attempt: int):
        verifier = NoticeVerifier(INDIA_RBI, india_rbi_corpus())
        subject = notice()
        first = verifier.verify(subject, _module_decision(), attempt=attempt)
        second = verifier.verify(subject, _module_decision(), attempt=attempt)
        assert first == second

    def test_an_empty_corpus_rejects_every_citation(self):
        verifier = NoticeVerifier(INDIA_RBI, InMemoryCorpus())
        result = verifier.verify(notice(), _module_decision())
        assert not result.passed
        assert ViolationCode.CITATION_VALIDITY in _codes(result)


def _module_decision() -> CreditDecision:
    """Build the reference decision.

    Hypothesis cannot take a function-scoped fixture, so the property tests
    construct their own copy.
    """
    return CreditDecision(
        application_id=APPLICATION_ID,
        probability_default=0.83,
        decision=Decision.DECLINE,
        threshold=0.15,
        model_version="xgb-test",
        feature_values=FEATURE_VALUES,
        factors=(
            _factor(ADVERSE_IDS[0], 1, FactorDirection.ADVERSE, 0.92),
            _factor(ADVERSE_IDS[1], 2, FactorDirection.ADVERSE, 0.81),
            _factor(ADVERSE_IDS[2], 3, FactorDirection.ADVERSE, 0.46),
            _factor(FAVOURABLE_IDS[0], 4, FactorDirection.FAVOURABLE, -0.22),
            _factor(FAVOURABLE_IDS[1], 5, FactorDirection.FAVOURABLE, -0.14),
        ),
        scored_at=datetime.now(UTC),
    )
